"""empty message

Revision ID: b954b89fea64
Revises: 99de2d65668f
Create Date: 2024-05-06 13:52:53.686860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b954b89fea64'
down_revision = '99de2d65668f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_type', sa.String(), nullable=False, server_default='Cool'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.drop_column('food_type')

    # ### end Alembic commands ###
