"""empty message

Revision ID: fb41b1f21572
Revises: b954b89fea64
Create Date: 2024-05-07 10:35:18.880626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb41b1f21572'
down_revision = 'b954b89fea64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('drink_type', sa.String(), nullable=False))

    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.alter_column('food_type',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Cool'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foods', schema=None) as batch_op:
        batch_op.alter_column('food_type',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Cool'"))

    with op.batch_alter_table('drinks', schema=None) as batch_op:
        batch_op.drop_column('drink_type')

    # ### end Alembic commands ###
